### PR TITLE
Update dep

### PR DESCRIPTION
**Pull request by jeveloper**
Updated peer dependency

### CODE REVIEW

**Comment by ProLoser** [comment]
It shouldn't matter as you can install any version greater than 1. Is there a reason you chose 1.1? (I have not been following the dev path)

**Comment by jeveloper** [comment]
When installing using bower (which is common) , this lib forces dependent lib of 1.0 , i set 1.1 just to make sure its not breaking anything . What if they change something you're dependent on in say version 1.2 or 2 , so 1.1 is safer.

thanks

**Comment by ProLoser** [comment]
@timelf123 does this make sense to you? ^ I'm a little confused by it. Has there been major changes that this repo would not be compatible with in 1.0? `^1.0.0` literally means the latest version as long as it's higher than `1.0.0`

**Comment by charlierudolph** [comment]
I believe the `bower.json` file needs to be updated so that the angularitics dependency uses a`^` instead of a `~`

**Comment by jeveloper** [comment]
Yes! thats right :(

**Comment by ProLoser** [comment]
@charlierudolph good catch. @jeveloper would you like to change this PR to what @charlierudolph prescribed? Or open a new one?

**Comment by timelf123** [comment]
AFAIK `^1.0.0` works just fine. Just fixed the bower file to reflect the same

**Comment by charlierudolph** [comment]
@timelf123 Thanks! Any chance you could release a new version? I'd like to take advantage of the update

**Comment by timelf123** [comment]
@charlierudolph https://github.com/angulartics/angulartics-segment/releases/tag/0.1.4

**Pull request closed without merging**
