### PR TITLE
do not pass `properties` to page view tracking

### LINKED ISSUE #10: $$ properties passed on pageviews
My segment pageviews look like:

``` javascript
analytics.page('http://dev.local:4000/', {
  $$protocol: 'http',
  $$host: 'dev.local',
  $$port: 4000,
  $$path: '',
  $$search: {},
  $$hash: '',
  $$url: '',
  $$absUrl: 'http://dev.local:4000/',
  $$state: null,
  $$replace: false,
  name: 'http://dev.local:4000/',
  path: '/',
  referrer: 'http://dev.local:4000/pricing/',
  search: '',
  title: 'Site Title',
  url: 'http://dev.local:4000/'
});
```

I don't think `$$properies` should be passed to segment. Probably they are inherited from angulartics itself, shouldn't they be filtered?

### PR DESCRIPTION
**Pull request by troex**
fixes #10

### CODE REVIEW

**Comment by ProLoser** [comment]
I think you'll encounter a lag of 1 route change if you do not pass the up-to-date information contained in `$location`

**Comment by troex** [comment]
nope it's all good, I've tested with example, there is no delay

**Comment by troex** [comment]
if you add `console.log(properties);` right before `.page()` call you will see:

screen shot 2016-05-17 at 00 25 58

there is absolutely no useful info for segment script, it won't parse angular private variables `$$` anyhow

**Comment by ProLoser** [comment]
@troex I have mixed feelings about this entire implementation but I can merge it however a new release needs to be cut. Do you want me to make you a collaborator on this repo?

**Comment by troex** [comment]
I've looked at other implementations and there is nothing wrong or different in yours, maybe except `angulartics.waitForVendorApi` call is being used lately.

You can make me a collaborator but I don't promise I'll look after project, I could do some fixes or accept PRs and maybe respond to some issues if there would be any.

**Comment by timelf123** [comment]
#17 wants props back on the basis that the page tracking api takes custom props
https://github.com/angulartics/angulartics/blob/master/src/angulartics.js#L192-L196 do we need to strip the `$$` from `$location` here?

https://segment.com/docs/sources/website/analytics.js/#page

**Pull request merged**
