### PR TITLE
Fixed page view to include properties as well

### PR DESCRIPTION
**Pull request by subramaniashiva**
Properties in the page method [can be overridden by user](https://segment.com/docs/sources/website/analytics.js/#page). So properties should also be passed to page method.

### CODE REVIEW

**Comment by natterstefan** [comment]
@subramaniashiva I agree with you, the `properties` should be available in the `page` method again (optionally of course). Currently I want to modify the Intercom Integration and display the Messenger Icon only on certain pages via the `page` method. It is [explained here](https://segment.com/docs/integrations/intercom/#conditionally-show-the-intercom-chat-widget). But I am not able to, as long as `properties` is missing.

Any news on this @ProLoser or @troex?

**Comment by ProLoser** [comment]
@hassanbazzi you still active?

**Comment by hassanbazzi** [comment]
@ProLoser Ehhh..... I can look at this.

The change looks simple enough. We can merge it. Conflicts though.

**Comment by ProLoser** [comment]
Conflicts are build files, which I wish we didn't have to commit, but alas
is a remnant of Bower support. I'd just rerun the build during merge
resolution and commit the results as the resolution of the conflict.

**Comment by ProLoser** [comment]
Would be nice if the CI server took care of that stuff.

**Comment by natterstefan** [comment]
Thank you for the quick response @ProLoser and @hassanbazzi. What was the reason that `properties` was removed?

**Comment by hassanbazzi** [comment]
Sorry dude, I forgot about you. Do you still need this? @natterstefan

**Comment by natterstefan** [comment]
@hassanbazzi Hi, no, not anymore. Thank you :)

**Pull request closed without merging**
